### ISSUE TITLE
希望可以增加一个能够设置使用了金银王冠后的属性颜色功能

### ISSUE THREAD

**Issue by Gateszaizi** [blank038/PokemonInfo#2]
例如玩家使用了王冠增加了hp的属性，那么在信息面板看到hp变成了红色

**Comment by Gateszaizi** [comment]
转换为相片或者展示的时候无法显示，最好还是可以都能显示

**Comment by blank038** [comment]
> 转换为相片或者展示的时候无法显示，最好还是可以都能显示

新的需求应该创建新的 issue 来跟进，此 issue 已关闭。
