### ISSUE TITLE
王冠修改的防御和特防是不是有问题

### ISSUE THREAD

**Issue by Dinosaur1616** [blank038/PokemonInfo#6]
用金色王冠修改的，显示双防是白色

**Comment by blank038** [comment]
请提供插件版本号，模组版本号，其他属性是否显示正常？

**Comment by Dinosaur1616** [comment]
v1.14.6  其他属性都正常是红色

**Comment by Dinosaur1616** [comment]
模组是9.1.11

**Comment by blank038** [comment]
fixes https://github.com/blank038/PokemonInfo/commit/2eaac66d4c65eb2f39e2ce482de4c9efe4433eed
